### ISSUE TITLE
Leader fails with securityContext defined

### ISSUE THREAD

**Issue by bdalpe** [criblio/helm-charts#127]
gosu cannot be installed when running as non-root

**Comment by bdalpe** [comment]
Additionally, the user IDs get formatted as scientific notation.

myapp-5bbb7468d5-pcvnl runAsUser: 1000620000

**Comment by kmccririe** [comment]
Note from customer:
Just trying to bring a test result at least into the uid issue. The large UID being attempted to run the cribl service is not an issue when adding with useradd and groupadd directly, but the Helm chart is converting them into scientific notation for anything larger than 6 decimal places.

An immediate work around would be to change the UID to a lower than 6 digits UID, which is not ideal. Enclosing the UID into double quotes works as well.
