### ISSUE TITLE
Remove `:` in role & rolebinding names

### ISSUE THREAD

**Issue by Kavinraja-G** [criblio/helm-charts#172]
I don't think it is good to have `:` in the names for [roles](https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-workergroup/templates/role.yaml#L6) & [rolebinding](https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-workergroup/templates/rolebinding.yaml#L6), is this required standard from Cribl side to have this naming convention?

I did faced some strange issues when deploying the helm chart for workerGroups via Terraform helm provider --
```
15:14:03  │ Error: malformed chart or values: 
15:14:03  │ 	templates/role.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context
15:14:03  │ 	templates/rolebinding.yaml: unable to parse YAML: error converting YAML to JSON: yaml: line 4: mapping values are not allowed in this context
```

**Comment by Kavinraja-G** [comment]
Hi, yes in my case as well I don't need the RBAC. This got resolved when I set [lint](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#lint) to `false` in the helm_release TF resource. But this still a workaround for now.

Chart Version: `4.2.1`

values.yaml -- I did set rbac.create to `false` only. But still the terraform helm linting making some weird issues here.
```yaml
rbac:
  create: false
  apiGroups:
  - core
  resources:
  - pods
  verbs:
  - get
  - list
  annotations: {}
```

**Comment by bdalpe** [comment]
At a minimum, the names should be enclosed in quotes. But I agree, it might be best to move to a naming pattern that doesn't include colons.

**Comment by Kavinraja-G** [comment]
@bdalpe I hope RBAC is not required even if we are using IRSA/WLI in GKE (use IAM roles to access AWS resources)?

**Comment by bdalpe** [comment]
@Kavinraja-G only `serviceAccount.create=true` is required in your values when using IRSA/WLI. You can leave `rbac.create=false`
