### ISSUE TITLE
Separate logstream-leader service and service-internal annotations

### ISSUE THREAD

**Issue by kenmoini** [criblio/helm-charts#182]
**Problem Statement:**
When deploying the logstream-leader Helm chart, some users may use the very common MetalLB LoadBalancer orchestrator when deploying on-premise.

When using MetalLB it's common to assign AddressPools and LoadBalancerIPs via annotations.

Currently the rendered `ls-leader` and the `ls-leader-internal` Services both use the same Service annotation definition inputs from the Helm chart values.  This causes issues since the `ls-leader-internal` should be referenced internally in the cluster by default, not exposed as a LoadBalancer type in most instances.

See:
- https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-leader/templates/service-internal.yaml#L9
- https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-leader/templates/service.yaml#L9

**Solution Option(s):**
- Separate the annotation keys in the Helm Chart values and templates as they are for the Service type, eg `Values.service.internalType` and `Values.service.externalType`

**Comment by bdalpe** [comment]
This is resolved with #183
