### ISSUE TITLE
Static PVC name leader-config-claim - can't deploy multiple Leaders in the same namespace

### ISSUE THREAD

**Issue by bdalpe** [criblio/helm-charts#196]

**Comment by konradmars** [comment]
It'd be great to have PVC configurable in https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-leader/values.yaml. Aside from multiple leaders issue, lack of it hurts a bit e.g. unable to control lifecycle of EBS Volume on AWS, etc.
