### ISSUE TITLE
Running as non-root requires privileged set to True

### ISSUE THREAD

**Issue by benji-york** [criblio/helm-charts#199]
I am working on getting the default Cribl Docker image to run as a non-root user.  That will require that the image be run as "privileged" so that the few capabilities that it does need can take effect.

I don't know much about Helm, but I think each chart will need a `securityContext` with `privileged: true`.

Here is a Docker file that works stand-alone and with Docker Compose, but only with privileged access.

```
# syntax=docker/dockerfile:1
FROM ubuntu:20.04
ARG TARGETARCH
# Create low-churn layer.
RUN apt-get update && \
    apt-get -y upgrade dpkg && \
    apt-get install --no-install-recommends -y \
        curl \
        jq \
        ca-certificates \
        git \
        openssh-client \
        iproute2 && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    adduser \
        --disabled-password \
        --disabled-login \
        --no-create-home \
        --system \
        --ingroup root \
        cribl
# Create high-churn layers.
COPY ./cribl-linux-* /tmp/
RUN echo $TARGETARCH | sed -e s/amd64/x64/ > /tmp/cribl-arch && \
    tar -zxvf /tmp/cribl-linux-$(cat /tmp/cribl-arch).tgz -C /opt && \
    rm /tmp/cribl-* && \
    chown -R cribl:root /opt/cribl && \
    setcap CAP_DAC_READ_SEARCH,CAP_SYS_PTRACE,CAP_NET_BIND_SERVICE,CAP_NET_ADMIN+eip \
        /opt/cribl/bin/cribl
ADD entrypoint.sh /sbin/entrypoint.sh
ENV DEMOUSER_NAME "Demo User"
ENV DEMOUSER_EMAIL "demo@cribl.io"
ENV CRIBL_INSTALL_TYPE "CONTAINER"
ENV GIT_DISCOVERY_ACROSS_FILESYSTEM=1
USER cribl
ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["cribl"]
```

Let me know how I can help ensure the change to run as a non-root user continues to work with our Helm charts.

**Comment by bdalpe** [comment]
@benji-york three things I'd recommend trying before setting `privileged: true`:

1. Build your container image with a [USER](https://docs.docker.com/reference/dockerfile/#user). This makes files owned by the appropriate user.
2. chown `/opt/cribl` using a `RUN` command in your Dockerfile.
3. Use the [`CRIBL_VOLUME_DIR`](https://docs.cribl.io/stream/environment-variables/) to set a writable path for Cribl configs. By default, it will try to write to various directories inside `/opt/cribl`. If you built your container using the root user (default if no `USER` is specified), then Cribl will be denied write access if `privileged: false`.

**Comment by benji-york** [comment]
@bdalpe, I'm a little confused.  The steps you outline are all represented in the Dockerfile I posted above, correct?

**Comment by benji-york** [comment]
OK, I think this will be a non-issue because I've decided not to change the default user for the `cribl/cribl` image from `root` to `cribl` but to instead let the end-user choose which to run under.  That means that existing Helm charts should work as expected.
