### ISSUE TITLE
Avoid .git ownership problems

### ISSUE THREAD

**Issue by bieron** [criblio/helm-charts#59]
https://github.blog/2022-04-18-highlights-from-git-2-36/

> Beginning in Git 2.35.2, Git changed its default behavior to prevent you from executing git commands in a repository owned by a different user than the current one. This is designed to prevent git invocations from unintentionally executing commands which the repository owner configured.

**Comment by bdalpe** [comment]
If `securityContext` is set, we should `chown` `$CRIBL_VOLUME_DIR` to avoid issues.
