### ISSUE TITLE
Support for custom labels

### ISSUE THREAD

**Issue by Kavinraja-G** [criblio/helm-charts#96]
I would like to have support for having custom labels to the Kubernetes resources and have it pass via the `values.yaml`.

I think we can probably add the custom lables support [here](https://github.com/criblio/helm-charts/blob/master/helm-chart-sources/logstream-leader/templates/_helpers.tpl#L35), something like --
```
{{- if .Values.labels}}
{{ toYaml .Values.labels }}
{{- end }}
```

**Comment by bdalpe** [comment]
Hi @Kavinraja-G, are you looking for the custom labels to be applied to all resources in the chart or a subset of them?

**Comment by Kavinraja-G** [comment]
@bdalpe -- Custom labels can be probably added to most of the resources which supports. (Labelling is really useful in K8s world like we use tags in AWS.)
